### ISSUE TITLE
Implement detail

### ISSUE THREAD

**Issue by gigaflw** [dyweb/hrs#1]
Some questions on the requirements described in https://github.com/dyweb/mos/issues/8

> other services in our team, like GitLab Tq, QA, etc.

Aren't GitLab tq or QA both website instead of any kind of 'service'?

> Self-service registration of our services like GitLab Tq, QA, etc.

What does 'self-service' mean? （seems a same question..）

> Other

It seems this project should also cover the management of the recruitment of new members, but this point is not covered in the listed requirements?

@ComMouse ❓

**Comment by ComMouse** [comment]
@GigaFlower 

1. You don't need to implement any features marked optional right now. A simple information collecting system is just ok.
2. My initial thought was that one that had registered our hr system could directly log in other services like GitLab Tq,, QA, etc. Ways to implement this goal include self-service registration (i.e. to register GitLab or other services by new comers themselves, which can be implemented by an API of that service with admin priviledge), single sign-on, etc.

**Comment by gigaflw** [comment]
So once a brand new comer with none of the accounts in GitLab Tq, QA, etc ... has registered in the hr system, he can login the hr system, click some cute button, then registration on other services completes automatically ? 
Well, then I think I get it, thx.

**Comment by gigaflw** [comment]
@ComMouse
I summarize https://github.com/dyweb/hrs/blob/master/design.md as the system's guideline,
since I realize I'm not familiar with backend when coding further.
Is there anything wrong or weird?

**Comment by gigaflw** [comment]
@ComMouse 
Although crude, basic parts of the hrs have been completed.
May I have your evaluation on the current system ?

**Comment by ComMouse** [comment]
LGTM @JasonQSY @arrowrowe @gaocegege 

https://github.com/dyweb/mos/issues/8

**Comment by ComMouse** [comment]
@GigaFlower Any time for tongqu?

**Comment by JasonQSY** [comment]
admire

**Comment by at15** [comment]
.w. btw: maybe have a docker file for people who don't have PHP environment (like me)

cc @GigaFlower @ComMouse

**Comment by gigaflw** [comment]
@ComMouse 
You mean the tongqu website? 
seems not much leisure recently, maybe one or week after the new term begins ?

**Comment by gigaflw** [comment]
And also this hrs needs much more work to complete all functionalities

**Comment by gigaflw** [comment]
@at15 
Seems good, I will try it.

**Comment by ComMouse** [comment]
@GigaFlower All right.

**Comment by at15** [comment]
... so what's current status @ComMouse

**Comment by ComMouse** [comment]
Fundamentally done long time ago....

**Comment by at15** [comment]
@ComMouse 基本做完了? ...

**Comment by ComMouse** [comment]
Yeah
